/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatDarculaLaf;
import br.com.caelum.stella.validation.CPFValidator;
import br.com.caelum.stella.validation.InvalidStateException;
import dao.ClienteDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modelo.Cliente;


/**
 *
 * @author Lincolzera
 */
public class Cadastrocliente extends javax.swing.JFrame {
        
    /**
     * Creates new form Cadastrocliente
     */
    public Cadastrocliente() {
       
                try {
            UIManager.setLookAndFeel( new FlatDarculaLaf() );
            UIManager.put( "TextComponent.arc", 15 );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FundoPanel = new javax.swing.JPanel();
        Form = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        read = new javax.swing.JButton();
        atualiza = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        Conta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FundoPanel.setBackground(new java.awt.Color(51, 51, 51));
        FundoPanel.setPreferredSize(new java.awt.Dimension(1200, 800));
        FundoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Form.setBackground(new java.awt.Color(51, 51, 51));
        Form.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");

        jTextField1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPF");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefone");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Endereço");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data de nascimento");

        jTextField6.setText("'aaaa-mm-dd'");

        read.setText("Ler cadastrados");
        read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readActionPerformed(evt);
            }
        });

        atualiza.setText("Atualizar cadastro");
        atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaActionPerformed(evt);
            }
        });

        remover.setText("Remover cadastro");
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormLayout = new javax.swing.GroupLayout(Form);
        Form.setLayout(FormLayout);
        FormLayout.setHorizontalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormLayout.createSequentialGroup()
                        .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FormLayout.createSequentialGroup()
                                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(read, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(atualiza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remover))))
                    .addGroup(FormLayout.createSequentialGroup()
                        .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19)
                        .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        FormLayout.setVerticalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormLayout.createSequentialGroup()
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(read)
                    .addComponent(cadastrar)
                    .addComponent(atualiza)
                    .addComponent(remover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sair)
                    .addComponent(limpar))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        FundoPanel.add(Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 590, 550));

        Conta.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 56)); // NOI18N
        Conta.setForeground(new java.awt.Color(255, 255, 255));
        Conta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Conta.setText("Crie aqui a sua conta");
        FundoPanel.add(Conta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, 60));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("registre-se em poucos passos!");
        FundoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 520, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Comece agora a transformar sua experiência");
        FundoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 520, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/Fundo.jpg"))); // NOI18N
        FundoPanel.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 600, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FundoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FundoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        CPFValidator validator = new CPFValidator();
        Cliente cliente = new Cliente();
        cliente.setNome(jTextField1.getText());
        cliente.setCpf(jTextField2.getText());
        cliente.setEmail(jTextField3.getText());
        cliente.setTel(jTextField4.getText());
        cliente.setEndereco(jTextField5.getText());
        cliente.setData_nasc(jTextField6.getText());
        
        
         try {
            validator.assertValid(jTextField2.getText());
            // Exibe uma mensagem de sucesso
            JOptionPane.showMessageDialog(null, "-> " + jTextField2.getText() + " é VÁLIDO (assertValid não lançou exceção).", "Validação bem-sucedida", JOptionPane.INFORMATION_MESSAGE);
        } catch (InvalidStateException e) {
            // Este bloco não deve ser executado para um CPF válido que passe no algoritmo
            // Exibe uma mensagem de erro
            JOptionPane.showMessageDialog(null, "-> " + jTextField2.getText() + " é INVÁLIDO: " + e.getInvalidMessages(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }


        // Validação da data de nascimento (AAAA-MM-DD)
        String dataNascimentoStr = cliente.getData_nasc();
        if (dataNascimentoStr != null && !dataNascimentoStr.isEmpty()) {
            Pattern pattern = Pattern.compile("^\\d{4}-\\d{2}-\\d{2}$");
            Matcher matcher = pattern.matcher(dataNascimentoStr);
            if (!matcher.matches()) {
                JOptionPane.showMessageDialog(null, "Data de nascimento inválida. Formato esperado: AAAA-MM-DD");
                return; // Impede a inserção se a data for inválida
            }
        }

        String emailStr = cliente.getEmail();

        if (emailStr != null && !emailStr.isEmpty()) {
            Pattern pattern = Pattern.compile("^.+@.+\\.com$");
            Matcher matcher = pattern.matcher(emailStr);
            if (!matcher.matches()) {
                JOptionPane.showMessageDialog(null, "O email está escrito de forma inválida. Formato esperado: NomeUsuário@email.com");
                return;
            }
        }

        String cpfStr = cliente.getCpf();

        if (cpfStr != null && !cpfStr.isEmpty()) {
            Pattern pattern = Pattern.compile("^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$");
            Matcher matcher = pattern.matcher(cpfStr);
            if (!matcher.matches()) {
                JOptionPane.showMessageDialog(null, "CPF inválido. Formato esperado: XXX.XXX.XXX-XX");
                return;
            }
            // CPF está no formato correto
        }
        
  

        // Validação de campos obrigatórios
        if (cliente.getNome().isEmpty() || cliente.getCpf().isEmpty() || cliente.getEmail().isEmpty() || cliente.getTel().isEmpty() || cliente.getEndereco().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios.");
        } else {
            ClienteDAO dao = new ClienteDAO();
            try {
                dao.adiciona(cliente);
            } catch (SQLException ex) {
                Logger.getLogger(Cadastrocliente.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");  
    }//GEN-LAST:event_limparActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readActionPerformed
        ClienteDAO dao = new ClienteDAO();
        VisualizarClienteGUI vc = new VisualizarClienteGUI();
        dao.ler(vc);
        vc.setVisible(true);
    }//GEN-LAST:event_readActionPerformed

    private void atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaActionPerformed
        Cliente cliente = new Cliente();
        cliente.setNome(jTextField1.getText().trim());
        cliente.setCpf(jTextField2.getText().trim());
        cliente.setEmail(jTextField3.getText().trim());
        cliente.setTel(jTextField4.getText().trim());
        cliente.setEndereco(jTextField5.getText().trim());
        cliente.setData_nasc(jTextField6.getText().trim());

  
        String dataNascimentoStr = cliente.getData_nasc();
        if (dataNascimentoStr != null && !dataNascimentoStr.isEmpty()) {
            Pattern pattern = Pattern.compile("^\\d{4}-\\d{2}-\\d{2}$");
            Matcher matcher = pattern.matcher(dataNascimentoStr);
            if (!matcher.matches()) {
                JOptionPane.showMessageDialog(null, "Data de nascimento inválida. Formato esperado: AAAA-MM-DD");
                return;
            }
        }


        if (cliente.getCpf().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o CPF para atualizar o cliente.");
        } else {
            ClienteDAO dao = new ClienteDAO();
            dao.atualiza(cliente);  // Chama o método de update
            JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso!");
        }
    }//GEN-LAST:event_atualizaActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        String cpfParaExcluir = jTextField2.getText().trim();

        if (cpfParaExcluir.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o CPF do cliente que deseja excluir.");
        } else {
            int confirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o cliente com CPF: " + cpfParaExcluir + "?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);

            if (confirmacao == JOptionPane.YES_OPTION) {
                ClienteDAO dao = new ClienteDAO();
                dao.deleta(cpfParaExcluir);
                JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso!");
            }
        }
    }//GEN-LAST:event_removerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrocliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Conta;
    private javax.swing.JPanel Form;
    private javax.swing.JPanel FundoPanel;
    private javax.swing.JButton atualiza;
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton limpar;
    private javax.swing.JButton read;
    private javax.swing.JButton remover;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
